[package]
name = "fqtl-rs"
version = "0.1.0"
edition = "2021"
rust-version = "1.87"
license = "MIT"
authors = ["Yongjin Park <ypp@stat.ubc.ca> <yongjin.park@ubc.ca>"]
description = "fqtl: functions for QTL analysis"
repository = "https://github.com/causalpathlab/fqtl-rs"
homepage = "https://github.com/causalpathlab/fqtl-rs"
readme = "README.md"
keywords = ["qtl", "gwas", "fine-mapping", "susie", "genomics"]
categories = ["science", "command-line-utilities"]

[[bin]]
name = "fqtl"
path = "src/main.rs"

[features]
default = []
cuda = ["candle-core/cuda", "candle-core/cudnn", "candle-nn/cuda"]
metal = [
    "candle-core/metal",
    "candle-core/accelerate",
    "candle-nn/metal",
    "candle-nn/accelerate",
]

[dependencies]
anyhow = "1.0"
clap = { version = "4.5.20", features = ["derive"] }
ctrlc = { version = "3", features = ["termination"] }
flate2 = "1.0.34"
num_cpus = "1.16.0"
rayon = "1.10.0"
tempfile = "3.2"
rand = "0.10.1"
rand_distr = "0.6"
nalgebra = "0.34"
nalgebra-sparse = "0.11"
approx = "0.5.1"
num-traits = "0.2.19"

special = "0.13"
statrs = "0.18"
indicatif = { version = "^0.18", features = ["rayon"] }
env_logger = "0.11"
log = "0.4"
dashmap = { version = "6.1.0", features = ["rayon"] }
rustc-hash = "2.1"

colored = "3"
rust-htslib = "1.0"

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

parquet = "59"
zip = "8"

candle-core = { version = "0.10", default-features = false }
candle-nn = { version = "0.10", default-features = false }
