[package]
name = "fqtl-rs"
license.workspace = true
authors.workspace = true
description.workspace = true
repository.workspace = true
homepage.workspace = true
edition.workspace = true
version = "0.1.0"

[[bin]]
name = "fqtl"
path = "src/main.rs"

[features]
default = []
cuda = [
    "candle-util/cuda",
    "matrix-util/cuda",
    "mcmc-util/cuda",
]
metal = [
    "candle-util/metal",
    "matrix-util/metal",
    "mcmc-util/metal",
]

[dependencies]
candle-util = { workspace = true }
matrix-util = { workspace = true }
mcmc-util = { workspace = true }
genomic-data = { workspace = true }

anyhow = { workspace = true }
clap = { workspace = true }
flate2 = { workspace = true }
num_cpus = { workspace = true }
rayon = { workspace = true }
tempfile = { workspace = true }
rand = { workspace = true }
rand_distr = { workspace = true }
nalgebra = { workspace = true }
nalgebra-sparse = { workspace = true }
approx = { workspace = true }

special = { workspace = true }
statrs = { workspace = true }
indicatif = { workspace = true }
env_logger = { workspace = true }
log = { workspace = true }
dashmap = { workspace = true }
rustc-hash = { workspace = true }

colored = { workspace = true }
rust-htslib = { workspace = true }

serde = { workspace = true }
serde_json = { workspace = true }
